# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python: 3.5
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pypy
    - TOX_ENV=pypy3
#    - TOX_ENV=flake8

script: tox -e $TOX_ENV

install:
    - pip install tox
    - pip install coverage
    - pip install pytest-cov
    - pip install codecov

after_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - codecov -e TOX_ENV

notifications:
  email: false